### ISSUE TITLE
暴露端口设置问题

### ISSUE THREAD

**Issue by CookedMelon** [GZTimeWalker/GZCTF-Challenges#1]
配置pwn动态flag时平台默认连接端口是80，同时xinetd.conf配置的暴露端口也默认为80，但是此时构建镜像后无法nc。但是把两个地方的80改为9999却又成功了

**Comment by GZTimeWalker** [comment]
此处所给示例的暴露端口均为 70，如有其他问题请附上相关配置文件和容器输出。

不过这并不是平台相关问题，所给建议仅供参考，具体题目构建问题请自主解决。
